// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountNotesByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetNoteByID(ctx context.Context, id uuid.UUID) (Note, error)
	GetNoteByIDAndUserID(ctx context.Context, arg GetNoteByIDAndUserIDParams) (Note, error)
	GetNoteByIDWithDeleted(ctx context.Context, id uuid.UUID) (Note, error)
	GetUserByEmail(ctx context.Context, email *string) (User, error)
	GetUserByEmailOrPhone(ctx context.Context, email *string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone *string) (User, error)
	HardDeleteNote(ctx context.Context, id uuid.UUID) error
	ListNotesByUserID(ctx context.Context, arg ListNotesByUserIDParams) ([]Note, error)
	ListNotesByUserIDWithDeleted(ctx context.Context, arg ListNotesByUserIDWithDeletedParams) ([]Note, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RestoreNote(ctx context.Context, arg RestoreNoteParams) error
	SoftDeleteNote(ctx context.Context, arg SoftDeleteNoteParams) error
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
